name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
on: [workflow_dispatch]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  check-githubactor:
    if: ${{ !contains(github.actor, 'abcd') }}
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.set-vars.outputs.branch-name }}
      proceed-with-build: ${{ steps\.set-vars.output.build-flag }}
    
    steps:
      - name: set env vars
        id: set-vars
        run: |
        BRANCH_NAME="${GITHUB_HEAD_REF}"
        echo $BRANCH_NAME
        echo "branch-name=$BRANCH_NAME" >> $GITHUB_OUTPUT

        flag=true
        echo $flag"
        echo "build-flag=$flag" >> $GITHUB_OUTPUT

        sri-flag=false
        echo $sri-flag
        echo "sri-flag=$sri-flag" >> $GITHUB_ENV

        env | sort | uniq

