name: Version Build

on:
  workflow_dispatch:

jobs:
  build-version:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Git version
      run: |
        ls -ltr
        touch test
        ls -ltr
        VERSION=${GITHUB_REF#refs/tags/v}
        MAJOR=${VERSION%%.*}
        echo "VERSION=$VERSION"
        echo "MAJOR=$MAJOR"
        git --version
        git tag
        echo test
        latest_version=`git tag --sort=taggerdate | tail -1`
        export major=`echo $latest_version | awk -F '.' '{print $1}'`
        export minor=`echo $latest_version | awk -F '.' '{print $2}'`
        export patch=`echo $latest_version | awk -F '.' '{print $3}'`
        export Latest_Tag=$major.$minor.$patch
        echo Latest_Tag=$Latest_Tag
        echo "show 1"
        git show $Latest_Tag
        echo "show 2"
        git show v1.0.0^{tree}
        echo "show 3"
        git show -s --format=%s v1.0.0^{commit}
        echo "show stop"
        patch=$(( $patch + 1 ))
        export Next_Tag=$major.$minor.$patch
        echo Next_Tag=$Next_Tag
