name: Version Build

on:
  workflow_dispatch:

jobs:
  build-version:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Git version
      run: |
        ls -ltr
        touch test
        ls -ltr
        VERSION=${GITHUB_REF#refs/tags/v}
        MAJOR=${VERSION%%.*}
        echo "VERSION=$VERSION"
        echo "MAJOR=$MAJOR"
        git --version
        git tag
        echo test
        git tag --sort=taggerdate | tail -1
