name: Versioning

on:
  workflow_dispatch:

jobs:
  movetag:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get major version num and update tag
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        MAJOR=${VERSION%%.*}
        echo "VERSION=$VERSION"
        echo "MAJOR=$MAJOR"
