name: Version Build

on:
  workflow_dispatch:

jobs:
  build-version:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Git version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        MAJOR=${VERSION%%.*}
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        echo git_hash=$git_hash
        latest_version=`git tag --sort=taggerdate | tail -1`
        export major=`echo $latest_version | awk -F '.' '{print $1}'`
        export minor=`echo $latest_version | awk -F '.' '{print $2}'`
        export patch=`echo $latest_version | awk -F '.' '{print $3}'`
        export current_latest_tag=$major.$minor.$patch
        echo current_latest_tag=$current_latest_tag
        git show $current_latest_tag
        patch=$(( $patch + 1 ))
        export new_tag=$major.$minor.$patch
        echo new_tag=$new_tag
        git tag $new_tag
        git push origin --tags
